name = "gnoga_options"
description = ""
version = "0.1.0-dev"

authors = ["Your Name"]
maintainers = ["Your Name <example@example.com>"]
maintainers-logins = ["github-username"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

project-files = "gnoga_options.gpr"

[[depends-on]]
ada_lib_base = "~0.1.0-dev"

[[pins]]
ada_lib_base = { path='../../ada_lib/ada_lib_base' }




