source ~/.zshrc
export WHICH=$1
echo WHICH $BUILD_MODE BUILD_PROFILE $ADA_APPLICATION_PROFILE ADA_OS_INCLUDE $ADA_OS_INCLUDE

../global_build.sh $BUILD_MODE gnoga_ada_lib $ADA_APPLICATION_PROFILE library
